// mp_railgun.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 32 total shaders

textures/mp_railgun/cable
{
	qer_editorimage textures/props/cable_m01.tga
	surfaceparm metalsteps
	{
		map textures/props/cable_m01.tga
		rgbGen vertex
	}
}

textures/mp_railgun/fog
{
	qer_editorimage textures/sfx/fog_grey1.tga
	fogparms ( 1 1 1 ) 2560
	surfaceparm fog
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
}

textures/mp_railgun/lmterrain_base
{
	q3map_lightmapMergable
	q3map_lightmapaxis z
	q3map_lightmapsize 512 512
	q3map_normalimage textures/sd_bumpmaps/normalmap_terrain.tga
	q3map_tcGen ivector ( 512 0 0 ) ( 0 512 0 )
	q3map_tcMod rotate 37
	q3map_tcMod scale 1 1
	surfaceparm landmine
	surfaceparm snowsteps
}

textures/mp_railgun/lmterrain_0
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_0to1
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_0to2
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_0to3
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_0to4
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_0to5
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_0to6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_1
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_1to2
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_1to3
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_1to4
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_1to5
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_1to6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_2
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_2to3
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_2to4
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_2to5
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_2to6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_3
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_3to4
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_3to5
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_3to6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_4
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_4to5
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_4to6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_5
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_5to6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

textures/mp_railgun/lmterrain_6
{
  qer_editorimage textures/detail_sd/snowdetail.tga
	surfaceparm snowsteps
	surfaceparm landmine
	{
		map $lightmap
		rgbGen identity
	}
	{
		map textures/detail_sd/snowdetail.tga
		blendFunc filter
	}
}

//textures/mp_railgun/sky
//{
//	qer_editorimage textures/skies/sky_6.tga
//	q3map_skylight 90 3
//	q3map_sun 0.55 0.55 0.55 90 220 60
//	skyparms - 200 -
//	surfaceparm nodlight
//	surfaceparm noimpact
//	surfaceparm nolightmap
//	surfaceparm sky
//}

textures/mp_railgun/sky
{
	qer_editorimage textures/skies/fueldump_clouds.tga
	q3map_lightrgb 0.8 0.9 1.0
	q3map_skylight 85 3
	q3map_sun 1 .95 .9 200 210 28
	skyparms - 200 -
	surfaceparm nodlight
	surfaceparm noimpact
	surfaceparm nolightmap
	surfaceparm sky
	{
		map textures/skies/fueldump_clouds.tga
		rgbGen identity
	}
	{
		map textures/skies/fueldump_clouds.tga
		blendfunc blend
		rgbGen identity
		tcMod scroll 0.0005 0.00
		tcMod scale 2 1
	}
}

